// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: device.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteDevice = `-- name: DeleteDevice :exec
DELETE FROM devices WHERE push_token = $1::text
`

func (q *Queries) DeleteDevice(ctx context.Context, pushToken string) error {
	_, err := q.db.Exec(ctx, deleteDevice, pushToken)
	return err
}

const getDeviceByPushToken = `-- name: GetDeviceByPushToken :one
SELECT id, user_id, platform, push_token, apns_environment, revoked_at, last_registered_at, created_at, updated_at FROM devices WHERE push_token = $1::text
`

// push_token は UNIQUE。RLS 下では自分の行だけ返る。
func (q *Queries) GetDeviceByPushToken(ctx context.Context, pushToken string) (Device, error) {
	row := q.db.QueryRow(ctx, getDeviceByPushToken, pushToken)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Platform,
		&i.PushToken,
		&i.ApnsEnvironment,
		&i.RevokedAt,
		&i.LastRegisteredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDevicesByUserID = `-- name: ListDevicesByUserID :many
SELECT id, user_id, platform, push_token, apns_environment, revoked_at, last_registered_at, created_at, updated_at FROM devices
WHERE user_id = $1::uuid
ORDER BY last_registered_at DESC
`

func (q *Queries) ListDevicesByUserID(ctx context.Context, userID pgtype.UUID) ([]Device, error) {
	rows, err := q.db.Query(ctx, listDevicesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Device{}
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Platform,
			&i.PushToken,
			&i.ApnsEnvironment,
			&i.RevokedAt,
			&i.LastRegisteredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const registerDevice = `-- name: RegisterDevice :one
SELECT id, user_id, platform, push_token, apns_environment, revoked_at, last_registered_at, created_at, updated_at FROM register_device(
    $1::text,
    $2::text,
    $3::text
)
`

type RegisterDeviceParams struct {
	Platform        string  `json:"platform"`
	PushToken       string  `json:"push_token"`
	ApnsEnvironment *string `json:"apns_environment"`
}

// push_token の upsert と所有者付け替えは RLS では書けないため関数に閉じる。
// 呼び出し前に SET LOCAL app.current_user_id が必要。
func (q *Queries) RegisterDevice(ctx context.Context, arg RegisterDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, registerDevice, arg.Platform, arg.PushToken, arg.ApnsEnvironment)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Platform,
		&i.PushToken,
		&i.ApnsEnvironment,
		&i.RevokedAt,
		&i.LastRegisteredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDevice = `-- name: UpdateDevice :one
UPDATE devices
SET
    platform = $1,
    apns_environment = $2,
    revoked_at = $3,
    updated_at = now()
WHERE id = $4
RETURNING id, user_id, platform, push_token, apns_environment, revoked_at, last_registered_at, created_at, updated_at
`

type UpdateDeviceParams struct {
	Platform        string             `json:"platform"`
	ApnsEnvironment *string            `json:"apns_environment"`
	RevokedAt       pgtype.Timestamptz `json:"revoked_at"`
	ID              pgtype.UUID        `json:"id"`
}

func (q *Queries) UpdateDevice(ctx context.Context, arg UpdateDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, updateDevice,
		arg.Platform,
		arg.ApnsEnvironment,
		arg.RevokedAt,
		arg.ID,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Platform,
		&i.PushToken,
		&i.ApnsEnvironment,
		&i.RevokedAt,
		&i.LastRegisteredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
