// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Availability struct {
	ID              pgtype.UUID        `json:"id"`
	GroupID         pgtype.UUID        `json:"group_id"`
	UserID          pgtype.UUID        `json:"user_id"`
	DurationMinutes int32              `json:"duration_minutes"`
	Message         *string            `json:"message"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	CancelledAt     pgtype.Timestamptz `json:"cancelled_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type AvailabilityResponse struct {
	ID             pgtype.UUID        `json:"id"`
	AvailabilityID pgtype.UUID        `json:"availability_id"`
	UserID         pgtype.UUID        `json:"user_id"`
	Action         string             `json:"action"`
	Source         string             `json:"source"`
	RespondedAt    pgtype.Timestamptz `json:"responded_at"`
}

type Device struct {
	ID               pgtype.UUID        `json:"id"`
	UserID           pgtype.UUID        `json:"user_id"`
	Platform         string             `json:"platform"`
	PushToken        string             `json:"push_token"`
	ApnsEnvironment  *string            `json:"apns_environment"`
	RevokedAt        pgtype.Timestamptz `json:"revoked_at"`
	LastRegisteredAt pgtype.Timestamptz `json:"last_registered_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type Group struct {
	ID         pgtype.UUID        `json:"id"`
	Name       string             `json:"name"`
	InviteCode string             `json:"invite_code"`
	CreatedBy  pgtype.UUID        `json:"created_by"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type GroupMember struct {
	ID       pgtype.UUID        `json:"id"`
	GroupID  pgtype.UUID        `json:"group_id"`
	UserID   pgtype.UUID        `json:"user_id"`
	Role     string             `json:"role"`
	JoinedAt pgtype.Timestamptz `json:"joined_at"`
	LeftAt   pgtype.Timestamptz `json:"left_at"`
}

type Notification struct {
	ID              pgtype.UUID        `json:"id"`
	Kind            string             `json:"kind"`
	AvailabilityID  pgtype.UUID        `json:"availability_id"`
	RecipientUserID pgtype.UUID        `json:"recipient_user_id"`
	Title           string             `json:"title"`
	Body            string             `json:"body"`
	Payload         []byte             `json:"payload"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	ExpandedAt      pgtype.Timestamptz `json:"expanded_at"`
}

type NotificationDelivery struct {
	ID              pgtype.UUID        `json:"id"`
	NotificationID  pgtype.UUID        `json:"notification_id"`
	DeviceID        pgtype.UUID        `json:"device_id"`
	Status          string             `json:"status"`
	ApnsID          *string            `json:"apns_id"`
	ErrorReason     *string            `json:"error_reason"`
	Attempts        int32              `json:"attempts"`
	LastAttemptedAt pgtype.Timestamptz `json:"last_attempted_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID          pgtype.UUID        `json:"id"`
	DisplayName string             `json:"display_name"`
	Email       *string            `json:"email"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type UserIdentity struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Provider  string             `json:"provider"`
	Subject   string             `json:"subject"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
