// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, display_name, email, created_at, updated_at FROM users WHERE email = $1::text
`

// email は NULL 可の列だが、引数として NULL を渡す意味はない
// （SQL の = は NULL と一致しない）。::text で非 NULL に固定する。
func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, display_name, email, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const registerUser = `-- name: RegisterUser :one
SELECT register_user(
    $1::uuid,
    $2::text,
    $3::text,
    $4::text,
    -- email は NULL 可。空文字のまま入れると、メールを持たない利用者が
    -- 2 人目から UNIQUE に当たる。NULL は重複とみなされない。
    $5::text
) AS user_id
`

type RegisterUserParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	Provider    string      `json:"provider"`
	Subject     string      `json:"subject"`
	DisplayName string      `json:"display_name"`
	Email       *string     `json:"email"`
}

// users と user_identities を 1 トランザクションで作る。
// 直接 INSERT すると、identity の無い users 行が残りうる。
//
// 返るのは落ち着き先の users.id。先に同じ sub で登録されていれば
// 渡した user_id とは違う値が返るため、呼び出し側は必ず受け取る。
func (q *Queries) RegisterUser(ctx context.Context, arg RegisterUserParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, registerUser,
		arg.UserID,
		arg.Provider,
		arg.Subject,
		arg.DisplayName,
		arg.Email,
	)
	var user_id pgtype.UUID
	err := row.Scan(&user_id)
	return user_id, err
}
