// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_identity.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const resolveUserIDByIdentity = `-- name: ResolveUserIDByIdentity :one
SELECT resolve_user_by_identity($1::text, $2::text) AS user_id
`

type ResolveUserIDByIdentityParams struct {
	Provider string `json:"provider"`
	Subject  string `json:"subject"`
}

// 認証ミドルウェアが app.current_user_id の確定前に呼ぶ。
// その時点では RLS で自分の行すら見えないため、SECURITY DEFINER 関数に委ねる。
// 未登録なら NULL が返る。
func (q *Queries) ResolveUserIDByIdentity(ctx context.Context, arg ResolveUserIDByIdentityParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, resolveUserIDByIdentity, arg.Provider, arg.Subject)
	var user_id pgtype.UUID
	err := row.Scan(&user_id)
	return user_id, err
}
